#!/bin/sh

export ROOT=$(dirname $0)
export PROG=$(basename $0)
export SUBS=${ROOT}/subcmd
export HELP=${ROOT}/help
export INDEX=${ROOT}/.mydts.index

_mytag_ds () {
    __inner () {
        for root in /Volumes /mnt /media /mount $HOME; do
            find $root -maxdepth 6 -name .mytags  2> /dev/null
        done
    }
    for xx in $(__inner); do
        echo $(dirname $xx)
    done
}

freshen () {
    echo "[$PROG]: refreshing cache ..." >&2
    t=/tmp/$RANDOM.$RANDOM
    _mytag_ds > ${t}
    mv ${t} ${INDEX}
}


case $1. in
    .|-h.|--help.)
        ${SUBS}/help
        exit
        ;;
    help.)
        shift
        ${SUBS}/help $*
        exit
        ;;
esac

[ ! -f ${INDEX} ] && freshen

[ "$1" = "-f"   ] && shift && freshen
[ "$1" = ""     ] && exit


[ ! -f ${SUBS}/$1 ] &&  echo ${PROG}: unrecognized subcommand: "[$1]"
[   -f ${SUBS}/$1 ] &&  ${SUBS}/$* && exit $?

