#!/bin/sh

#d# List tags

usage () { cat << EOF
USAGE:
    $PROG $SUB -a         : list all tags
    $PROG $SUB -d <DIR>   : list tags from dir <DIR>
EOF
}
SUB=$(basename $0)
[ "$1" = "-h" ] && usage && exit
[ "$1" = "--help" ] && usage && exit
#[ "$1" = "" ] && usage && exit

source ${ROOT}/bin/activate

case $1. in
    -d.)
        /bin/ls -1 "$2/.mytags"
        exit
        ;;
    -a.)
        _mytag_ts
        ;;
    *)
        $PROG help $(basename $0)
        ;;
esac

