#!/bin/sh

#d# Remove a tag from a directory

usage () { cat << EOF
USAGE:
    $PROG $SUB <dir> <tag>          : remove tag from dir
EOF
}
SUB=$(basename $0)
[ "$1" = "-h" ] && usage && exit
[ "$1" = "--help" ] && usage && exit
#[ "$1" = "" ] && usage && exit

NAME=$(basename $0)
tagfile=${1}/.mytags/${2}

help () { $PROG help $NAME; }

[ "$1" == ""        ] && { help; exit; }
[ "$1" == "-h"      ] && { help; exit; }
[ "$1" == "--help"  ] && { help; exit; }
[ ! -d "${1}"       ] && echo "not a dir: [${1}]" && exit 87
[ -f ${tagfile}     ] && rm ${tagfile}
