#!/bin/sh

#d# List tagged dirs

usage () { cat << EOF
USAGE:
        $PROG $SUB -a           : list all tagged dirs
        $PROG $SUB -t <TAG>     : list all dirs with tag <TAG>
EOF
}
SUB=$(basename $0)
[ "$1" = "-h" ] && usage && exit
[ "$1" = "--help" ] && usage && exit
#[ "$1" = "" ] && usage && exit

source ${ROOT}/bin/activate

NAME=$(basename $0)

case $1. in
    -a.)
        _mytag_ds
        ;;
    -t.)
        for dir in $(_mytag_ds); do
            [ -f ${dir}/.mytags/$2 ] && echo ${dir}
        done
        ;;
    *)
        $PROG help $NAME
        ;;
esac


