#!/usr/bin/env bash

#d# Print this help!
#d#
#d#     This is before      the blank
#d#
#d#      This is after  the blank
#d#

doc4cmd () {
    cmd=${SUBS}/${1}
    while IFS= read -r line;
        do
            aa=$( echo "$line" | cut -c -3 )
            bb=$( echo "$line" | cut -c 5- )
            [ ! "${aa}" = '#d#' ] && continue
            [ $2. = --oneline. ] && echo ${bb} && break
            echo "        ${bb}"
        done < ${cmd}
}

general () {
    echo USAGE:
    echo "        $PROG SUBCOMMAND"
    echo
    echo SUBCOMMANDS:
    for cmd in $(/bin/ls ${SUBS}); do
     printf "       "
     printf '%-16s' "${cmd} "
     printf "$(doc4cmd $cmd --oneline)\n"

    done
}

special () {
    cmd=$1
    [ ! -f ${SUBS}/${cmd} ] && {
      echo "not a subcommand: [${cmd}]"
      exit
    }
    echo USAGE:
    echo "        $PROG ${cmd}"
    echo
    echo DOCUMENTATION:
    doc4cmd ${cmd}
}


[ -z "$1" ] && general || special $1
