#!/bin/sh

#d# Supply help on subcommands

usage () { cat << EOF
USAGE:
    $PROG $SUB      : supply help on subcommands
EOF
}
SUB=$(basename $0)
[ "$1" = "-h" ] && usage && exit
[ "$1" = "--help" ] && usage && exit

doc4cmd () {
    cmd=${SUBS}/${1}
    while IFS= read -r line;
        do
            aa=$( echo "$line" | cut -c -3 )
            bb=$( echo "$line" | cut -c 5- )
            [ ! "${aa}" = '#d#' ] && continue
            [ $2. = --oneline. ] && echo ${bb} && break
            echo "        ${bb}"
        done < ${cmd}
}

general () {
    echo USAGE:
    echo "        $PROG SUBCOMMAND"
    echo "        $PROG SUBCOMMAND -h"
    echo
    echo SUBCOMMANDS:
    for cmd in $(/bin/ls ${SUBS}); do
        printf "       "
        printf '%-10s' "${cmd} "
        printf "$(doc4cmd $cmd --oneline)\n"
    done
}

special () {
    cmd=$1
    [ ! -f ${SUBS}/${cmd} ] && {
      echo "not a subcommand: [${cmd}]"
      exit
    }
    $PROG ${cmd} -h
    return
}


[ -z "$1" ] && general || special $1
