#!/bin/sh

SUB=$(basename $0)
META=$1
TARGET=$2

#d# Inject a unique tag.

usage () {
cat << EOF
USAGE:
    $PROG $SUB <TAG> <DIR>

    Add tag to dir if it would make it unique.
EOF
}

case $1. in
    .|-h.|--help.)
        usage
        exit
        ;;
esac

mydts isuniq $META

case $? in
    1)
        echo "[$PROG $SUB]: Injecting tag [$META] into [$TARGET]"
        mkdir -p $TARGET
        mydts add $TARGET $META
        ;;

esac
